"use client";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Saira } from "@next/font/google";

const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
          <main className={`${saira.variable}`}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
